/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package technical_test_waizly_mobile

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'technical_test_waizly_mobile.greeting' plugin.
 */
class Technical_test_waizly_mobilePluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("technical_test_waizly_mobile.greeting")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
